### ISSUE TITLE
Question re: Sequence and Memory displays, and @available

### ISSUE THREAD

**Issue by jslusser** [petervanhoef/Calculator-Brain#13]
Now that I've added the Memory display to the storyboard, I'm having trouble getting my Memory and Sequence displays to render the full width of the display (i.e. like I was able to in Assignment I).  I figured out how to add the new Memory display, create a horizontal stack, add constraints, add a blank space in the text field of each (so they at least initially display in the storyboard), however they are bunched up on the left side of the screen, and then automatically resize depending on the text contained in each at a particular time.  I've compared my code to yours to no avail, but obviously must be missing something somewhere.  Any thoughts on where in my code I should look?

Re: @available, I think I understand what you did, but can you please point me somewhere to read more on deprecation?  I don't understand the syntax of  @available(*, deprecated, message: "Use evaluate instead"), and was trying to learn more about it - and the Xcode documentation has many "deprecation" entries, but all seemingly very case -specific and no general explanation.  Thanks in advance.

**Comment by jslusser** [comment]
I figured out the Memory and Sequence display issue - still researching deprecation...

**Comment by petervanhoef** [comment]
Regarding the layout: I was also struggling with adding the constraints. There is a note added to task 8 describing how I solved that (see #5).

Regarding `@available`: see the comments to task 5: #3 . There is a reference to the Swift documentation: [The Swift Programming Language (Swift 3.1): Attributes](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Attributes.html)

**Comment by jslusser** [comment]
Many thanks.  Apologies for the delay in closing this issue 😳 ...now on to the Graphing assignment!
